### ISSUE TITLE
Discuss

### ISSUE THREAD

**Issue by vmos0** [Grill-Laux/kernel_oneplus_sdm845#4]
之前的信息被删除了没看到，请问下触屏问题是否解决了？

**Comment by uwu-gl** [comment]
是亮度问题（没遇到）还是触屏一点不能用的问题（已解决）？

**Comment by vmos0** [comment]
> 是亮度问题（没遇到）还是触屏一点不能用的问题（已解决）？

之前你说的屏幕触屏不能点的问题是否已解决？

**Comment by uwu-gl** [comment]
> > 是亮度问题（没遇到）还是触屏一点不能用的问题（已解决）？
> 
> 之前你说的屏幕触屏不能点的问题是否已解决？

解决啦，就是一个乌龙问题，现在内核基本大毛病没有了

**Comment by vmos0** [comment]
> > > 是亮度问题（没遇到）还是触屏一点不能用的问题（已解决）？
> > 
> > 
> > 之前你说的屏幕触屏不能点的问题是否已解决？
> 
> 解决啦，就是一个乌龙问题，现在内核基本大毛病没有了

小毛病多吗？

**Comment by ShuaiB-SB233** [comment]
> > > > 是亮度问题（没遇到）还是触屏一点不能用的问题（已解决）？
> > > 
> > > 
> > > 之前你说的屏幕触屏不能点的问题是否已解决？
> > 
> > 
> > 解决啦，就是一个乌龙问题，现在内核基本大毛病没有了
> 
> 小毛病多吗？

亮度触摸已经修复吗，自动旋转可能有BUG，开机的时候爆一大堆错，进UI需要快开机的时候开投屏，我正在尝试最新内核（49337）

**Comment by uwu-gl** [comment]
> > > > 是亮度问题（没遇到）还是触屏一点不能用的问题（已解决）？
> > > 
> > > 
> > > 之前你说的屏幕触屏不能点的问题是否已解决？
> > 
> > 
> > 解决啦，就是一个乌龙问题，现在内核基本大毛病没有了
> 
> 小毛病多吗？

没测试过，基本是不多了，毕竟一加官方仓库还是比较好对付的

**Comment by uwu-gl** [comment]
基本没有啥问题了吧 我关了

**Comment by vmos0** [comment]
> 基本没有啥问题了吧 我关了

基本没问题了，剩下升级下zstd版本，打ksu和lxc补丁以及nethunter补丁，再看看有没有其它需要优化的地方

**Comment by uwu-gl** [comment]
> > 基本没有啥问题了吧 我关了
> 
> 基本没问题了，剩下升级下zstd版本，打ksu和lxc补丁以及nethunter补丁，再看看有没有其它需要优化的地方

ksu和lxc都打好了
另外，zstd有没有什么commit我可以直接借鉴一下吗？不知道可不可以直接抄pixel experience内核的zstd更新

**Comment by vmos0** [comment]
> > > 基本没有啥问题了吧 我关了
> > 
> > 
> > 基本没问题了，剩下升级下zstd版本，打ksu和lxc补丁以及nethunter补丁，再看看有没有其它需要优化的地方
> 
> ksu和lxc都打好了 另外，zstd有没有什么commit我可以直接借鉴一下吗？不知道可不可以直接抄pixel experience内核的zstd更新
大佬有时间可以打下nethunter补丁看能不能打上，nethunter补丁打上应该是没问题的
嘻嘻bbrplus补丁也可以打下https://raw.githubusercontent.com/UJX6N/bbrplus-4.9/main/convert_official_linux-4.9.x_src_to_bbrplus.patch
