### ISSUE TITLE
Grill-Laux/AnyKernel3无分支upstream & docker support

### ISSUE THREAD

**Issue by p1aintiff** [Grill-Laux/kernel_oneplus_sdm845#7]
```
ut@DESKTOP-07LEFCF:~$ git clone https://github.com/Grill-Laux/AnyKernel3 anykernel -b upstream
Cloning into 'anykernel'...
fatal: Remote branch upstream not found in upstream origin
```

**Comment by p1aintiff** [comment]
action 可以直接用，不建议使用自己的电脑编译。

**Comment by uwu-gl** [comment]
https://github.com/uwu-gl/kernel_oneplus_sdm845/commit/17641d7e0c74e7af2a00f966354a9be124653a8b
https://github.com/uwu-gl/kernel_oneplus_sdm845/commit/33d18e555bf32593aa7a4e85f729f09b869eb847
感谢指正！已修改
Thanks @p1aintiff

**Comment by uwu-gl** [comment]
@p1aintiff OxygenOS内核里面docker有什么不对的地方嘛？O⁠_⁠o
